### ISSUE TITLE
feature.xml - require import stanza

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-dev-tools-eclipse#30]
currently feature.xml in liberty-mpls does not contain a requires-import stanza listing the mpls.jdt.core plugin (and others)  but catagory.xml does specify a install repository for that plugin.  (and others)

The liberty-mpls plugin does install and the required dependency plugins install as well form the update site built during the build.

Investigate if this is correct - or do we need an entry in feature.xml as well?

**Comment by scottkurz** [comment]
We have #18 already for the feature.xml
