### ISSUE TITLE
LS functionality should be available in the Java Editor within eclipse

### ISSUE THREAD

**Issue by ajm01** [OpenLiberty/liberty-dev-tools-eclipse#32]
Currently only a subset of LS functions appear to work when a file is opened in the Java Editor in eclipse. All LS functions work when a file is opened in the Generic Editor, however.

Need to understand why this is and ensure that all LS function is working when a java part is opened in the Java Editor.

**Comment by scottkurz** [comment]
We solved this with: https://github.com/OpenLiberty/liberty-dev-tools-eclipse/commit/ee832d21a33b6159bcafd7ea089d927e49d6764c  .   Closing.
